# Generated by Django 5.0.3 on 2024-04-15 18:43

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True, verbose_name='Ключ')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('data', django_jsonform.models.fields.JSONField(verbose_name='Данные')),
                ('schema', models.JSONField(verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='settings_si_id_cd3e04_idx')],
            },
        ),
    ]
