# Generated by Django 5.0.6 on 2024-05-26 12:36

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("picture", models.ImageField(upload_to="")),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_uz", models.CharField(max_length=255, null=True)),
                ("tools", models.CharField(max_length=255)),
                ("tag", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("description_ru", models.TextField(null=True)),
                ("description_uz", models.TextField(null=True)),
                ("tools_description", models.TextField()),
                ("tools_description_ru", models.TextField(null=True)),
                ("tools_description_uz", models.TextField(null=True)),
                ("picture", models.ImageField(upload_to="")),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("socials", django_jsonform.models.fields.JSONField()),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telegram", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_uz", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_ru", models.TextField(null=True)),
                ("description_uz", models.TextField(null=True)),
                ("year", models.CharField(max_length=9)),
                ("client", models.CharField(max_length=255)),
                ("preview", models.ImageField(upload_to="")),
                ("content_picture", models.ImageField(upload_to="")),
                ("service", models.ManyToManyField(to="portfolio.service")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
