# Generated by Django 5.0.6 on 2024-05-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
