# Generated by Django 5.0.6 on 2024-05-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_delete_sitesettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="inquiry",
            options={"verbose_name": "Запрос", "verbose_name_plural": "Запросы"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="client",
            name="picture",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.CharField(max_length=255, verbose_name="Клиент"),
        ),
        migrations.AlterField(
            model_name="project",
            name="content_picture",
            field=models.ImageField(
                upload_to="", verbose_name="Контентное изображение"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="project",
            name="preview",
            field=models.ImageField(upload_to="", verbose_name="Превью"),
        ),
        migrations.AlterField(
            model_name="project",
            name="service",
            field=models.ManyToManyField(to="portfolio.service", verbose_name="Услуга"),
        ),
        migrations.AlterField(
            model_name="project",
            name="year",
            field=models.CharField(max_length=9, verbose_name="Год"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="service",
            name="picture",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="service",
            name="tag",
            field=models.CharField(max_length=255, verbose_name="Тэг"),
        ),
        migrations.AlterField(
            model_name="service",
            name="tools",
            field=models.CharField(max_length=255, verbose_name="Инструмент"),
        ),
        migrations.AlterField(
            model_name="service",
            name="tools_description",
            field=models.TextField(verbose_name="Описание инструментов"),
        ),
        migrations.AlterField(
            model_name="service",
            name="tools_description_ru",
            field=models.TextField(null=True, verbose_name="Описание инструментов"),
        ),
        migrations.AlterField(
            model_name="service",
            name="tools_description_uz",
            field=models.TextField(null=True, verbose_name="Описание инструментов"),
        ),
    ]
