# Generated by Django 5.0.6 on 2024-05-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_client_options_alter_inquiry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="project",
            name="show_at_main",
            field=models.BooleanField(
                default=True, verbose_name="Показывать на главной странице"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
