# Generated by Django 5.0.6 on 2024-07-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0004_client_active_project_active_project_show_at_main_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="year",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Год"
            ),
        ),
    ]
