# Generated by Django 5.0.6 on 2024-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_service_short_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="Эксперты в цифровом мире, где креатив и инновации объединяются. Вместе создаем уникальный след вашего бизнеса онлайн, обеспечивая рост и успех.",
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description_ru",
            field=models.TextField(
                blank=True,
                default="Эксперты в цифровом мире, где креатив и инновации объединяются. Вместе создаем уникальный след вашего бизнеса онлайн, обеспечивая рост и успех.",
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description_uz",
            field=models.TextField(
                blank=True,
                default="Эксперты в цифровом мире, где креатив и инновации объединяются. Вместе создаем уникальный след вашего бизнеса онлайн, обеспечивая рост и успех.",
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
    ]
