# Generated by Django 5.0.6 on 2024-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_service_short_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_header",
            field=models.CharField(
                default="123", max_length=255, verbose_name="Заголовок описания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="description_header_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Заголовок описания"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="description_header_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Заголовок описания"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tools_description_header",
            field=models.CharField(
                default="123",
                max_length=255,
                verbose_name="Заголовок описания инструментов",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="tools_description_header_ru",
            field=models.CharField(
                max_length=255,
                null=True,
                verbose_name="Заголовок описания инструментов",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tools_description_header_uz",
            field=models.CharField(
                max_length=255,
                null=True,
                verbose_name="Заголовок описания инструментов",
            ),
        ),
    ]
