# Generated by Django 5.0.6 on 2024-07-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_service_description_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="content_video",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Контентное видео"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="content_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Контентное изображение",
            ),
        ),
    ]
