# Generated by Django 5.0.1 on 2024-02-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='Only administrators will receive notifications', verbose_name='Is admin')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='Joined date')),
                ('last_update_date', models.DateTimeField(auto_now_add=True, verbose_name='Last update date')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Last name')),
                ('has_blocked_the_bot', models.BooleanField(default=False, verbose_name='Blocked the bot')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'indexes': [models.Index(fields=['id'], name='bot_telegra_id_4efb80_idx'), models.Index(fields=['is_admin'], name='bot_telegra_is_admi_c1de92_idx')],
            },
        ),
    ]
