# Generated by Django 5.0.6 on 2024-05-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_telegramaccount_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramaccount",
            name="first_name",
            field=models.CharField(max_length=64, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="telegramaccount",
            name="has_blocked_the_bot",
            field=models.BooleanField(default=False, verbose_name="Заблокировал бота"),
        ),
        migrations.AlterField(
            model_name="telegramaccount",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Только администраторы будут получать уведомления",
                verbose_name="Является админом",
            ),
        ),
        migrations.AlterField(
            model_name="telegramaccount",
            name="joined_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата подключения"
            ),
        ),
        migrations.AlterField(
            model_name="telegramaccount",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="telegramaccount",
            name="last_update_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="telegramaccount",
            name="username",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Юзернейм"
            ),
        ),
    ]
